import { Link, useParams } from "react-router-dom";
import { Badge } from "@/components/ui/Badge";
import { EmptyState } from "@/components/ui/EmptyState";
import { ForjaIcon, type ForjaIconName } from "@/design-system/forja/src/icons";
import { ExerciseMediaPlaceholder } from "@/features/exercises/components/ExerciseMediaPlaceholder";
import { ExerciseOverview } from "@/features/exercises/components/ExerciseOverview";
import { PrescriptionMetric } from "@/features/exercises/components/PrescriptionMetric";
import type { ExerciseRelation } from "@/features/exercises/domain/exercise";
import { getExerciseById } from "@/features/exercises/data/exercises";

function ContentPanel({ title, icon, items, tone }: { title: string; icon: ForjaIconName; items: string[]; tone?: string }) { if (!items.length) return null; return <section className={`coaching-panel ${tone ? `coaching-panel--${tone}` : ""}`}><h3><ForjaIcon name={icon} size={22} />{title}</h3><ul>{items.map((item,index) => <li key={`${index}-${item}`}>{item}</li>)}</ul></section>; }
function RelationGroup({ title, icon, items }: { title:string; icon:ForjaIconName; items:ExerciseRelation[] }) { if(!items.length)return null; return <div><h3><ForjaIcon name={icon} size={21}/>{title}</h3>{items.map((item,index)=><div className="relation" key={`${index}-${item.label}`}>{item.targetId ? <Link to={`/exercises/${item.targetId}`}><strong>{item.label}</strong></Link>:<strong>{item.label}</strong>}{item.description&&<p>{item.description}</p>}</div>)}</div>; }
function DetailHeading({ eyebrow,title,description }: { eyebrow:string; title:string; description?:string }) { return <div className="section-heading"><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{description&&<p>{description}</p>}</div>; }

export function ExerciseDetailPage() {
  const { exerciseId = "" } = useParams(); const exercise = getExerciseById(exerciseId);
  if (!exercise) return <div className="page"><EmptyState title="Ejercicio no encontrado" description="El identificador solicitado no existe entre las fichas utilizables." /><Link className="button" to="/exercises">Volver al catálogo</Link></div>;
  const {identity,classification,context,media,prescription,coaching,decision,relations,safety,whatToRecord,traceability}=exercise;
  const contextItems=[...context.requirements,...context.environment,...context.space,...context.surface];
  const methodological=[...decision.chooseWhen.map((item)=>`Elegir cuando: ${item}`),...decision.avoidWhen.map((item)=>`Evitar cuando: ${item}`),...traceability.methodologicalNotes];
  return <article className="page exercise-detail">
    <nav className="breadcrumbs" aria-label="Migas de pan"><Link to="/exercises">Ejercicios</Link><span aria-hidden="true">/</span><span>{identity.id}</span></nav>
    <header className="exercise-hero"><div className="exercise-hero__copy"><p className="eyebrow">{identity.id} · {classification.category}</p><h1>{identity.displayName}</h1>{identity.aliases.length>0&&<p className="exercise-aliases">También: {identity.aliases.join(" · ")}</p>}<p className="hero-objective">{identity.description}</p><div className="badge-list">{classification.capabilities.map((tag)=><Badge key={tag.id} icon={tag.icon} tone="blue">{tag.label}</Badge>)}{context.equipment.map((tag)=><Badge key={tag.id} icon={tag.icon}>{tag.label}</Badge>)}</div><dl className="identity-list"><div><dt>Patrón</dt><dd>{classification.movementPattern.label}</dd></div><div><dt>Contenido</dt><dd>Utilizable · primera versión</dd></div><div><dt>Media</dt><dd>{media.status === "missing" ? "Pendiente" : "Parcial"}</dd></div></dl></div><div className="exercise-hero__media">{media.masterImage.src?<img src={media.masterImage.src} alt={media.masterImage.alt??""}/>:<ExerciseMediaPlaceholder exercise={exercise}/>}</div></header>

    <ExerciseOverview exercise={exercise}/>
    <section className="detail-section detail-section--objective"><DetailHeading eyebrow="Propósito" title="Objetivo"/><p className="objective-copy">{identity.objective}</p></section>
    <section className="detail-section"><DetailHeading eyebrow="Dosificación" title="Prescripción" description="Variables aplicables a esta tarea. Los valores concretos dependen del objetivo y del contexto."/><div className="metrics-grid">{prescription.variables.map((metric)=><PrescriptionMetric key={`${metric.kind.type}-${metric.kind.key}`} metric={metric}/>)}</div>{prescription.contextualExample.length>0&&<div className="context-example"><h3>Ejemplo contextual</h3><ul>{prescription.contextualExample.map((item,index)=><li key={`${index}-${item}`}>{item}</li>)}</ul><p><ForjaIcon name="observe" size={19}/>{prescription.contextNote}</p></div>}</section>
    {(coaching.setup.length>0||contextItems.length>0)&&<section className="detail-section"><DetailHeading eyebrow="Antes de empezar" title="Preparación"/><div className="coaching-grid coaching-grid--two"><ContentPanel title="Preparar la tarea" icon="sets" items={coaching.setup}/><ContentPanel title="Requisitos y contexto" icon="observe" items={contextItems}/></div></section>}
    <section className="detail-section"><DetailHeading eyebrow="Ejecución" title="Cómo realizarla"/><div className="instruction-layout"><ol className="instruction-steps">{coaching.execution.map((item,index)=><li key={`${index}-${item}`}><span>{index+1}</span><p>{item}</p></li>)}</ol><ContentPanel title="Consignas posibles" icon="quality" items={coaching.cues} tone="success"/></div></section>
    <section className="detail-section"><DetailHeading eyebrow="Observación" title="Coaching" description="Indicadores para valorar la tarea sin exigir una solución estética universal."/><div className="coaching-grid coaching-grid--two"><ContentPanel title="Indicadores de competencia" icon="competence" items={coaching.competencyIndicators} tone="success"/><ContentPanel title="Errores relevantes" icon="modifyTask" items={coaching.commonErrors} tone="danger"/><ContentPanel title="Variabilidad aceptable" icon="observe" items={coaching.acceptableVariations} tone="warning"/><ContentPanel title="Seguridad y parada" icon="quality" items={[...safety.warnings,...coaching.stopCriteria]} /></div></section>
    <section className="detail-section"><DetailHeading eyebrow="Red de decisiones" title="Modificar la tarea" description="Las relaciones proceden de la ficha documental; no representan una progresión universal."/><div className="relations-grid relations-grid--adaptive"><RelationGroup title="Regresiones" icon="makeMoreAccessible" items={relations.regressions}/><RelationGroup title="Progresiones" icon="increaseDemand" items={relations.progressions}/><RelationGroup title="Sustituciones" icon="modifyTask" items={relations.substitutions}/><RelationGroup title="Variantes" icon="range" items={relations.variations}/><RelationGroup title="Ejercicios relacionados" icon="coordination" items={relations.relatedExercises}/></div></section>
    {whatToRecord.length>0&&<section className="detail-section"><DetailHeading eyebrow="Seguimiento" title="Qué registrar"/><ContentPanel title="Información útil para decidir" icon="sets" items={whatToRecord}/></section>}
    {methodological.length>0&&<section className="detail-section"><DetailHeading eyebrow="Criterio FORJA" title="Notas metodológicas"/><ContentPanel title="Selección y trazabilidad" icon="observe" items={methodological}/></section>}
  </article>;
}
